version: "3"
services:
  mongo:
    container_name: mongo-server
    image: mongo:5.0.7
    restart: always
    ports:
      - "27017:27017"

  api:
    container_name: api-container
    build: ./server
    image: api-server
    ports:
      - "3333:3333"
    command: npm start
    links:
      - mongo
    depends_on:
      - mongo


networks:
  default:
    name: linklab_net