version: "3"
services:
  mongo:
    container_name: mongo-server
    image: mongo:5.0.7
    network_mode: host
    restart: always
    ports:
      - "27017:27017"

  api:
    container_name: api-container
    build: ./server
    image: api-server
    network_mode: host
    ports:
      - "3333:3333"
    command: npm start
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://127.0.0.1:27017/products

  client:
    container_name: client-container
    build: ./client
    network_mode: host
    ports:
      - 3000:3000
    working_dir: /client
    depends_on:
      - api
