import { HeaderDesktop } from "@/components/HeaderDesktop";
import Head from "next/head";

export default function Page() {
  return <>
    <Head>
      <title>Linklab</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" imageSrcSet="@/../public/favicon.ico" />
    </Head>
    <main>
      <HeaderDesktop />
    </main>
  </>
}