import { Header } from "@/components/Header";
import { HeaderMobile } from "@/components/HeaderMobile";
import { OptionsCard } from "@/components/OptionsCard";
import { queryClient } from "@/services/queryClient";
import Head from "next/head";
import { QueryClientProvider } from "react-query";

export default function Page() {
  return <>
    <Head>
      <title>Linklab</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" imageSrcSet="@/../public/favicon.ico" />
    </Head>
    <QueryClientProvider client={ queryClient }>
      <Header />
      <HeaderMobile />
      <OptionsCard />
    </QueryClientProvider>
  </>
}